name: receive

on: push 

jobs: 
  openshift:
    name: test-e2e
    runs-on: ubuntu-latest
    steps:

    - name: Wait for build to succeed
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: dispatch
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        checkName: dispatch
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Do something with a passing build
      if: steps.wait-for-build.outputs.conclusion == 'success'

    - name: Do something with a failing build
      if: steps.wait-for-build.outputs.conclusion == 'failure'